# Generated by Django 2.2.6 on 2019-10-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESEARCH_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='gene_id',
            new_name='orthologs',
        ),
    ]
